### ISSUE TITLE
Custom Potion effects chest drop? 

### ISSUE THREAD

**Issue by MissPolgara** [2008Choco/DragonEggDrop#14]
I love your plugin and edited all dragons names egg's and lore.

but the chest drop items i want a custom potion to spawn. I can create them with command blocks but would like to move them as a drop item.
below is one of the dragons files and what I tried as the code. but didn't work. 

https://pastebin.com/EWB0VEGA

Pic of acustom potion i made with command blocks that I like implemented into my dragons drops 
https://drive.google.com/file/d/1gA4IE8AxFcnHFkDWc5locNI2WvOpFPtQ/view?usp=sharing

if i know the coding layout i can customize potion for each dragon.

**Comment by 2008Choco** [comment]
As it stands currently, DragonEggDrop does not support custom potion items. I've wanted to rewrite how the plugin parses items for quite some time and I think now would be the best time to do so. :)

**Comment by MissPolgara** [comment]
Well let me know when you add it.
I think it would be a great addition
Thanks for the fast response
________________________________

**Comment by 2008Choco** [comment]
How is this for a more flexible approach to item data? 😄

```yaml
loot:
  '1':
    weight: 1.0
    type: stick
    damage: 1
    amount: 1
    display-name: '&bExample Item'
    lore:
    - '&6Configure me'
    - '&6to any item'
    enchantments:
      unbreaking: 1
    banner-patterns:
      bricks: red
      bri: purple
    book-data:
      author: 2008Choco
      title: The Best Book Ever!
      generation: original
      pages:
      - "This is the first page of the book. Turn the page for an awesome surprise!"
      - "SURPRISE!"
    knowledge-book-recipes:
    - "minecraft:crafting_table"
    leather-color:
      r: 255
      g: 0
      b: 255
    potion:
      color:
        r: 255
        g: 255
        b: 255
      effects:
        '1':
          effect: speed
          duration: 600
          amplifier: 1
          ambient: true
          particles: false
          icon: false
        '2':
          effect: strength
          duration: 300
          amplifier: 2
          ambient: false
          particles: true
          icon: true
    skull-owner: 2008Choco
    fish-bucket-data:
      pattern-color: red
      body-color: black
      pattern: spotty
```
Plenty more options for people to use. I'm still writing out the parser for it, but it's about 75% done at this point. Fireworks will also be supported I'm just unsure how I want to lay that all out. Of course that example lays out every single option available, but when writing the loot it won't be that long and the plugin will yell at you if you use data you shouldn't be using (for example, trying to add potion data to a stick will warn you in the console and ignore the item)
