### ISSUE TITLE
Allow custom NBT data storage.

### ISSUE THREAD

**Issue by ItWasEnder** [2008Choco/DragonEggDrop#30]
I want to request a feature be added to be able to store all item NBT data. I want this so I can store items from other plugins, like a voucher from the vouchers plugin. Right now the plugin only stores default minecraft NBT data like damage. See below for example. 

I feel like this would honestly make your plugin 1000% better since it will allow for unlimited types of loot drops!

Voucher NBT Data: [https://imgur.com/4WJU2Sq.jpg](https://imgur.com/4WJU2Sq.jpg)

Dragon Config
```yml
  '2':
    weight: 1.0
    type: GLOBE_BANNER_PATTERN
    amount: 1
    damage: 97
    display-name: §aKit Scroll §7(Slayer)
    enchantments:
      power: 1
      punch: 1
      luck_of_the_sea: 1
    lore:
    - §7Use this to claim kit §eSlayer§7.
    - §7§l(§6§l!§7§l) §7Right click to redeem.
```
