### ISSUE TITLE
Invulnerable Endercrystals + Dragon Respawning 

### ISSUE THREAD

**Issue by darth123321** [2008Choco/DragonEggDrop#4]
Title is pretty self explanatory. This plugin on occasion spawns in endercrystals in the middle (where the end portal spawns after killing the enderdragon) that cannot be broke or targeted regardless of the command. Am currently unsure on how to deal with this and how to get rid of them.

Also the enderdragon after death does not always respawn regardless of the seconds chosen for it to do so. Am also not sure what is causing this or why its happening.

No errors are thrown back in console, and reloading the plugin does not help either. Unloading the plugin completely allows the destroying of the endercrystals.

**Comment by 2008Choco** [comment]
I will do some testing to attempt to reproduce this issue in a few minutes. If I can reproduce it, I'll try to make a fix. Others have reported the same issue

**Comment by 2008Choco** [comment]
I've executed this test 5 times in a row flawlessly without any crystals being invulnerable at all. If you could provide me with your configuration options that would be greatly appreciated

**Comment by darth123321** [comment]
Hi 2008Choco,

I appreciated your quick response. It's weird that you aren't receiving the same error that I am, although my error doesn't occur every time. Hopefully it is just something on my end and an easy fix!

Here is my config (if you'd prefer an attached copy just let me know).

```yaml
# DO NOT REMOVE OR MODIFY #
version: 2
# ----------------------- #

perform-update-checks: false

# All data involving the particle effects displayed after the death of the Ender Dragon
Particles:
    # The Y location the reward object will spawn at
    egg-start-y: 180.0
    
    # Type of particle, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    type: 'FLAME'
    
    # The number of particles to spawn per particle iteration
    amount: 4
    
    # Extra data of the particle (Most are not affected by this value)
    extra: 0
    
    # The particle offsets for each direction
    x-offset: 0.001
    y-offset: 0.001
    z-offset: 0.001
    
    # The speed multiplier at which particles will be spawned (how fast they will descend)
    speed-multiplier: 1
    
    # The amount of particle lines that will animate from the ceiling
    stream-count: 6
    
    # How often to spawn the particles (in ticks)
    interval: 1
    
    # Advanced particle functionality! DO NOT TOUCH UNLESS YOU UNDERSTAND WHAT THIS DOES
    Advanced:
        # A pre-defined mathematical shape for the particles to be displayed in
        # (Available: "BALL", "HELIX", "OPEN_END_HELIX", "CUSTOM")
        preset-shape: 'OPEN_END_HELIX'
        
        # The mathematical expression in which particles will be spawned along the x coordinate
        x-coord-expression: 'cos(theta)'
        
        # The mathematical expression in which particles will be spawned along the z coordinate
        z-coord-expression: 'sin(theta)'

# Number of lightning entities to spawn on egg land
lightning-amount: 4

# Drop type (egg, chest, chance, all). Option to drop a loot chest instead of an egg.
# Loot items are defined in loot.yml via command /ded addloot
# The 'all' type places every item defined in the loot.yml into the chest one time each.
drop-type: egg

# If chance, what is the percent chance of spawning a chest?(0 - 100)
chest-spawn-chance: 0

# Want a custom title for the loot chest? Set it here.
loot-chest-title: 'Loot Chest'

# Number of items in a loot chest
min-loot: 0
max-loot: 0

# Set a custom name and lore for the egg item (optional)
# The variable, "%dragon", will be replaced with the name of the killed dragon
# NOTE: Only eggs broken/dropped in the end world without
# existing ItemMeta will receive the below name/lore.
egg-name: "%dragon%'s Egg"
egg-lore: []

# Respawn dragon on join? (delay is in seconds)
respawn-on-join: true
join-respawn-delay: 21600

# Respawn dragon on death? (delay is in seconds)
respawn-on-death: true
death-respawn-delay: 21600

# Whether the countdown will run even when out of the end
countdown-across-world: true

# Announce respawn to end world players via the action bar.
announce-respawn: true

# Announcement message animation
announce-messages:
- '&6Dragon respawning in &e%formatted-time%'
- '&eDragon respawning in &6%formatted-time%'

# Give the dragon a custom name, bar style and bar colour. Or not, your choice.
# If more than one option, one will be chosen at random.
# Names do support color/format codes i.e. &4 (red).
# Set to: dragon-names: [] for none.
# Format: "name=DRAGON'S NAME|style=STYLE|color=COLOR"
# format and style are optional. See their respective Javadocs for valid values
# Style: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
# Colour: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
dragon-names:
- "name=&8Tilenth, Lord of Death|style=SEGMENTED_20|color=PURPLE"
```

Thanks again for your help! If you need any other information don't hesitate to reach out to me.

Yours,
darth
